### ISSUE TITLE
speaksLang uses .has on an Array

### ISSUE THREAD

**Issue by DianeOfTheMoon** [napolitanod/Token-Says#107]
The speaksLang function in say.js was changed to use `.has()` but on an Array.  I believe this should be `.includes()`.  As it stands, functionality with polyglot seems to be broken.

**Comment by napolitanod** [comment]
thank you for this pull request - the prior update to for treatment as a set was due to dnd5e updates. For whatever reason I thought Polyglot was only dnd5e. I have updated the code to use the Polyglot api to check for languages and this is in 1.11.3

Please give that a shot within your system and let me know if there is still an issue

**Comment by DianeOfTheMoon** [comment]
Yep, works great. :)
