### ISSUE TITLE
PF2e Effects/Conditions Improvements

### ISSUE THREAD

**Issue by harrisog** [napolitanod/Token-Says#119]
- Sayings are not respecting Activation Conditions set under the Trigger tab.

- Sayings are not being triggered by the Dead condition. Possibly it is implemented as a vanilla active effect instead of via the system's Effect item.

- Some (but not all) conditions in the pf2e system have values appended (e.g., Sickened 2, Stunned 1). Currently this module requires an exact match to fire a trigger, but It would probably be preferable in most use cases if these values were ignored -- telling the module to just listen for "Frightened" instead of "Frightened _X_". Alternately, being able to specify a range and/or wildcard operator would be a more granular solution to cover all use cases.

**Comment by napolitanod** [comment]
I believe 1.11.8 addresses issue 1.

Issue 2 I don't have a resolution for that doesn't delve into coding for system unique idiosyncrasies and having to manage what dead actually means across all scenarios in pf2e which I am not going to code into this module. There is a dead flag on the actor but this is derived from other data so there is not a hook I can watch where this change is passed in consistently. The overlay is passed in for the token but that doesn't handle all situations. In any case, I am handling dead for condition activation because I can check for the flag, assuming the flag on the actor is always correct.

Bullet 3 I will work on once Token Says is in foundry v11

**Comment by napolitanod** [comment]
With 1.12.0 (requires foundry v11 when you are ready to take upgrade) you will be able to perform wild card search for the action names. I am closing this out because the second bullet does not have a direct support in pf2e that I found (a hook that indicates dead condition added or removed) and bullet 1 and 3 should now be done.
