### ISSUE TITLE
Compability with other systems

### ISSUE THREAD

**Issue by PrometeuszV3** [napolitanod/Token-Says#131]
Good day
I discovered this module and was absolutely stunned by its quality and expansion.
Unfortunately, from what I've read from the description, the system is only suitable for advanced use (setting triggers, e.g., for saying something while performing an attack) with DnD and PF. Is it possible to configure the module in the same way on other systems?
I am mainly concerned with the Lancer TTRPG system.

**Comment by napolitanod** [comment]
I think the best approach here would be for a member of the Lancer community to develop a companion module for handling the Lancer specific actions. The Token Says API can be utilized to generate the sayings, so the companion module would just need to handle identifying when the event generates and then calling the API accordingly. If an API  or constant is not available within the Token Says module to fulfil a companion module need please submit a request and I can support that. 

At this time I don't have the time to support more systems - it's work enough to keep up to date with Foundry updates but when systems change their data models or means of generating events it also breaks the Token Says integration so adopting a new system isn't just the work to set it up to begin with but to maintain it going forward. Though Token Says does include integrations with PF1 and PF2e, it has been a learning experience as to the time commitment needed to properly set up integrations with systems I don't play in order to learned and then code to the system nuances and edge cases.
