### ISSUE TITLE
Attack roll triggers plays sound twice

### ISSUE THREAD

**Issue by MN88** [napolitanod/Token-Says#40]
With only DAE, MIDI-qol and token says active, attack roll sounds play twice, with a 50-100ms delay.

**Comment by napolitanod** [comment]
Good afternoon,

I am not able to recreate, but it may be due to differing midiQol settings. 

1. Can you first please confirm that you do not have the same audio set to trigger for another action type for the given token (e.g. on damage or item name or in response to an attack) where that either has a blank action name or matching to the attack roll that is duplicating the sound.
2. If that is not it, can you please export your midiQol settings and attach to this issue? Thanks!
3. Please let me know if you are on the latest version of Token Says and what Foundry version you are on.
Thanks!

**Comment by MN88** [comment]
it turns out your first potential reason was indeed the explanation. Thanks for the fast reply!

**Comment by napolitanod** [comment]
glad it was an easy thing!
