### ISSUE TITLE
(Suggestion) Compatibility with Polyglot?

### ISSUE THREAD

**Issue by ArdonDaros** [napolitanod/Token-Says#42]
Hello! First of all, this is an amazing module! Thank you for releasing this to the wider Foundry community. This module has added a layer of immersion and roleplay I have craved! 

I don't know how you feel about suggestions, and I don't know if my suggestion is even feasible to achieve, but I believe this module could benefit from compatibility with the Polyglot module. By compatibility I mean a settings option within the configuration window where the user could select a specific Polyglot language for each "Token Says".

That is, if I have a specific Token Says rollable table for drow npcs, I could edit the Token Says settings to make sure the speech generated by the drow through Token Says appears as "Undercommon", thus obfuscating the text for player characters who do not speak Undercommon, but revealing/translating the text for those who do. Technically, all it would do is add a layer of immersion / roleplay value.

In any case, thanks for reading! I greatly enjoy this module! Cheers!

**Comment by napolitanod** [comment]
Thank you for using the module. This should be possible. Token Says already includes some Polyglot integration - the token will speak in chat or in chat bubble using the currently selected language for that user (based on the Polyglot dropdown in chat). However, I don't think this will work as well in some situations, such as token responses, because the responding token may not also speak the language. It should be feasible to give that as a saying option and pass it to Polyglot. Thanks for the suggestion! I'll let you know when I have it implemented.

- Dan

**Comment by napolitanod** [comment]
The latest release (1.6) will let you associate a language to a saying if you have polyglot. If set, only tokens with that language that meet the saying condition will speak and it will be in that language. Please let me know if this solves what you were hoping for it to do. (I also added movement-based triggers in this release).

**Comment by ArdonDaros** [comment]
> The latest release (1.6) will let you associate a language to a saying if you have polyglot. If set, only tokens with that language that meet the saying condition will speak and it will be in that language. Please let me know if this solves what you were hoping for it to do. (I also added movement-based triggers in this release).

Thank you! The integration is exactly what I was hoping. Super amazing work!
