### ISSUE TITLE
[Very Little Feature Request] Add a pack of macro examples

### ISSUE THREAD

**Issue by p4535992** [napolitanod/Token-Says#53]
Is it possible to add a small pack of example macros to use the module? I found out that several people (myself included XD) start more quickly in using the module if starting from some macro examples.
In particular, macro examples relating to:
- show a random message
- play random audio
- show a random message and play a random audio
are the most requested.

**Comment by napolitanod** [comment]
Hello - I added a couple bare macros examples with the new release along with documentation inside the macro. Hopefully this helps get you started. Until I actually include audio files or rolltables with the module I can't really do much beyond the bare stuff. There are 2 API calls so I have a macro example for each. One of them only triggers sayings that are created in the world so with that I cannot provide a useable example because this module comes with no premade sayings.

**Comment by p4535992** [comment]
don't worry you did too much! it was a "Very Little Feature Request" a desired one. Thank you so much for taking the time to do this so fast.

**Comment by p4535992** [comment]
For me this is done too , TY !!!!
