### ISSUE TITLE
Token says doesn't work with damage rolls and midi-qol when "Merge rolls to one card" setting is checked

### ISSUE THREAD

**Issue by DawidIzydor** [napolitanod/Token-Says#60]
Combining token says with damage rolls when "Merge rolls to one card" setting in midi-qol is checked results in no message.

Steps to reproduce
1. Enable token says and midi-qol
2. Create token say roll table and configure a token to use it when dealing damage
2. Go to Midi-qol configuration->Misc->uncheck "Merge rolls to one card"
3. Token says a rolled message [OK]
4. Go to Midi-qol configuration->Misc->check "Merge rolls to one card"
5. Token no more says anything after dealing damage [BUG]

**Comment by napolitanod** [comment]
Thank you for reporting this along with the steps to reproduce. I should have time this weekend to look this over and see how to address.

Dan

**Comment by napolitanod** [comment]
Good morning - I had some time to look into this this morning and I am not able to recreate. The damage from Midi triggers a token says saying whether or not the merge rolls to one card is checked. 

My guess is that the cause is that you have 'Auto check if attack hits target' setting = 'Check - only GM sees' while also having the Token Says Setting 'Suppress Tokens Says on Private GM Rolls' checked. Then, when the chat cards are set to merge the whisper flag is present in both the attack and damage workflows for Midi because both are merging into the same chat message. That's my guess at least.

Token Says reads that selection as a whispered attack roll because from what I have gathered in the midiQol workflow, midi uses the same flag for whispering attack as it does to indicate a private roll (in the workflow data). If I ignore that flag then whispered attacks and damages in midiQol will trigger sayings even if 'Suppress Tokens Says on Private GM Rolls' is checked. 

If you want the whispered rolls to trigger sayings you can uncheck 'Suppress Tokens Says on Private GM Rolls' in the config settings and you should then see the saying generate. That setting is there to prevent a saying from giving away that a roll donr privately is doing something. Or you can change it so 'Auto check if attack hits target' setting allows all to see.

Please give that a shot.

Dan
